"""
Operation Primitives for Poincaré Computing

Operations transform coordinates in partition space. They are the
"instructions" in the compiled physics language.

Key insight: Operations are IRREVERSIBLE. This is not a limitation
but a feature - it's where thermodynamics comes from.

Three fundamental operations:
1. Partition: Divide (creates entropy)
2. Compose: Join (cannot recover partition entropy)
3. Traverse: Navigate (move through partition space)

The irreversibility relation: Partition(X) → Compose(Y) ≠ X
This is the second law of thermodynamics as a primitive.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional, Tuple, Dict, Any, List, Callable
from enum import Enum, auto
import time
import math

from .coordinates import (
    PartitionCoordinate,
    SCoordinate,
    TerminalState,
    CoordinateConstraint,
)


# Boltzmann constant for entropy calculations
K_B = 1.380649e-23  # J/K


class OperationType(Enum):
    """Classification of primitive operations."""
    PARTITION = auto()   # Divide into parts
    COMPOSE = auto()     # Join parts together
    TRAVERSE = auto()    # Navigate through space
    MEASURE = auto()     # Extract coordinate value
    TRANSFORM = auto()   # Change coordinate representation


@dataclass
class OperationResult:
    """
    Result of applying an operation.

    Every operation produces:
    - The resulting coordinate(s)
    - Entropy generated (always >= 0)
    - Lag time (real hardware time consumed)
    - Metadata about the operation

    Attributes:
        operation_type: Which operation was applied
        input_coords: Coordinates before operation
        output_coords: Coordinates after operation
        entropy_generated: ΔS in J/K (always >= 0)
        lag_ns: Hardware time in nanoseconds
        timestamp: When operation completed
        metadata: Additional operation-specific data
    """
    operation_type: OperationType
    input_coords: List[SCoordinate | PartitionCoordinate]
    output_coords: List[SCoordinate | PartitionCoordinate]
    entropy_generated: float
    lag_ns: int
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_irreversible(self) -> bool:
        """Check if operation generated entropy (irreversible)."""
        return self.entropy_generated > 0

    @property
    def entropy_in_k_B(self) -> float:
        """Entropy in units of k_B."""
        return self.entropy_generated / K_B


@dataclass
class PartitionOp:
    """
    Partition operation: divide a coordinate into parts.

    This is the fundamental entropy-generating operation.
    Partitioning creates categorical distinctions where none existed.

    S_partition = k_B * ln(n)

    where n is the number of parts.

    The partition lag (real time taken) is fundamental - it's
    where the entropy comes from. No free lunch.

    Attributes:
        n_parts: Number of parts to create
        residue_fraction: Fraction "lost" to undetermined residue
    """
    n_parts: int = 2
    residue_fraction: float = 0.01

    def __post_init__(self):
        if self.n_parts < 2:
            raise ValueError(f"n_parts must be >= 2, got {self.n_parts}")
        if not (0 <= self.residue_fraction < 1):
            raise ValueError(f"residue_fraction must be in [0, 1), got {self.residue_fraction}")

    @property
    def entropy(self) -> float:
        """Entropy generated by this partition: S = k_B * ln(n)."""
        return K_B * math.log(self.n_parts)

    def apply(self, coord: SCoordinate) -> OperationResult:
        """
        Apply partition to an S-coordinate.

        Divides the coordinate into n_parts, spreading across S-space.
        """
        start_time = time.perf_counter_ns()

        # Partition spreads the coordinate across S-space
        output_coords = []
        for i in range(self.n_parts):
            # Each part gets a fraction of the original uncertainty
            # plus new uncertainty from the partition itself
            fraction = (1.0 - self.residue_fraction) / self.n_parts
            offset = i / self.n_parts

            new_coord = SCoordinate(
                S_k=min(1.0, coord.S_k * fraction + offset * 0.1),
                S_t=min(1.0, coord.S_t * fraction + (1 - offset) * 0.1),
                S_e=min(1.0, coord.S_e + self.entropy / K_B * 0.01),
            )
            output_coords.append(new_coord)

        lag_ns = time.perf_counter_ns() - start_time

        return OperationResult(
            operation_type=OperationType.PARTITION,
            input_coords=[coord],
            output_coords=output_coords,
            entropy_generated=self.entropy,
            lag_ns=lag_ns,
            metadata={
                "n_parts": self.n_parts,
                "residue_fraction": self.residue_fraction,
            }
        )

    def cascade(self, coord: SCoordinate, depth: int = 3) -> List[OperationResult]:
        """
        Apply cascading partitions.

        Total entropy: S = k_B * depth * ln(n_parts)
        """
        results = []
        current_coords = [coord]

        for d in range(depth):
            new_results = []
            for c in current_coords:
                result = self.apply(c)
                new_results.append(result)
            results.extend(new_results)
            current_coords = [c for r in new_results for c in r.output_coords]

        return results


@dataclass
class ComposeOp:
    """
    Compose operation: join coordinates together.

    This is the inverse direction of partition, but critically:
    IT CANNOT RECOVER THE ENTROPY GENERATED BY PARTITION.

    Compose(Partition(X)) ≠ X

    This asymmetry is the second law of thermodynamics.

    Attributes:
        mode: How to combine coordinates ("mean", "min", "max", "weighted")
        weights: Optional weights for weighted composition
    """
    mode: str = "mean"
    weights: Optional[List[float]] = None

    def apply(self, coords: List[SCoordinate]) -> OperationResult:
        """
        Compose multiple S-coordinates into one.

        Note: Cannot recover entropy lost in partition.
        """
        if not coords:
            raise ValueError("Cannot compose empty list of coordinates")

        start_time = time.perf_counter_ns()

        if self.mode == "mean":
            result_coord = SCoordinate(
                S_k=sum(c.S_k for c in coords) / len(coords),
                S_t=sum(c.S_t for c in coords) / len(coords),
                S_e=sum(c.S_e for c in coords) / len(coords),
            )
        elif self.mode == "min":
            result_coord = SCoordinate(
                S_k=min(c.S_k for c in coords),
                S_t=min(c.S_t for c in coords),
                S_e=min(c.S_e for c in coords),
            )
        elif self.mode == "max":
            result_coord = SCoordinate(
                S_k=max(c.S_k for c in coords),
                S_t=max(c.S_t for c in coords),
                S_e=max(c.S_e for c in coords),
            )
        elif self.mode == "weighted" and self.weights:
            total_weight = sum(self.weights[:len(coords)])
            result_coord = SCoordinate(
                S_k=sum(c.S_k * w for c, w in zip(coords, self.weights)) / total_weight,
                S_t=sum(c.S_t * w for c, w in zip(coords, self.weights)) / total_weight,
                S_e=sum(c.S_e * w for c, w in zip(coords, self.weights)) / total_weight,
            )
        else:
            raise ValueError(f"Unknown composition mode: {self.mode}")

        lag_ns = time.perf_counter_ns() - start_time

        # Composition generates NO entropy (but doesn't recover partition entropy)
        return OperationResult(
            operation_type=OperationType.COMPOSE,
            input_coords=coords,
            output_coords=[result_coord],
            entropy_generated=0.0,  # Composition is reversible in isolation
            lag_ns=lag_ns,
            metadata={"mode": self.mode}
        )


@dataclass
class TraverseOp:
    """
    Traverse operation: navigate through partition space.

    Traversal moves from one coordinate to another. The path taken
    matters - different paths generate different entropy.

    This is the "dynamics" in Poincaré computing, but defined
    geometrically rather than through differential equations.

    Attributes:
        target: Where to traverse to
        path_type: "direct", "geodesic", "minimum_entropy"
        max_steps: Maximum traversal steps
    """
    target: SCoordinate | PartitionCoordinate
    path_type: str = "direct"
    max_steps: int = 100

    def apply(
        self,
        start: SCoordinate,
        step_size: float = 0.1
    ) -> OperationResult:
        """
        Traverse from start to target.

        Returns the path taken and entropy generated.
        """
        start_time = time.perf_counter_ns()

        # Convert target to SCoordinate if needed
        if isinstance(self.target, PartitionCoordinate):
            target_s = SCoordinate.from_partition(self.target)
        else:
            target_s = self.target

        path = [start]
        current = start
        total_entropy = 0.0

        for step in range(self.max_steps):
            distance = current.distance_to(target_s)

            if distance < step_size:
                # Close enough - snap to target
                path.append(target_s)
                break

            # Interpolate toward target
            t = min(1.0, step_size / distance)
            next_coord = current.interpolate(target_s, t)

            # Each step generates a small amount of entropy
            # (traversal through partition space is not free)
            step_entropy = K_B * math.log(1 + 1/distance) * 0.01
            total_entropy += step_entropy

            path.append(next_coord)
            current = next_coord

        lag_ns = time.perf_counter_ns() - start_time

        return OperationResult(
            operation_type=OperationType.TRAVERSE,
            input_coords=[start],
            output_coords=path,
            entropy_generated=total_entropy,
            lag_ns=lag_ns,
            metadata={
                "path_type": self.path_type,
                "steps_taken": len(path) - 1,
                "final_distance": current.distance_to(target_s),
            }
        )


@dataclass
class MeasureOp:
    """
    Measure operation: extract coordinate value.

    Measurement couples the observer to the system. This is where
    the categorical structure becomes physical.

    Measurement is NOT a passive reading - it establishes
    partition coordination through frequency matching.

    Attributes:
        target_dimension: Which dimension to measure ("S_k", "S_t", "S_e", "all")
        precision: Measurement precision (affects entropy)
    """
    target_dimension: str = "all"
    precision: float = 0.001

    def apply(self, coord: SCoordinate) -> OperationResult:
        """
        Measure the coordinate.

        Measurement generates entropy proportional to precision.
        """
        start_time = time.perf_counter_ns()

        # Measurement entropy: finer precision = more entropy
        measurement_entropy = K_B * math.log(1 / self.precision)

        # Extract values based on target dimension
        if self.target_dimension == "S_k":
            measured = {"S_k": coord.S_k}
        elif self.target_dimension == "S_t":
            measured = {"S_t": coord.S_t}
        elif self.target_dimension == "S_e":
            measured = {"S_e": coord.S_e}
        else:
            measured = {"S_k": coord.S_k, "S_t": coord.S_t, "S_e": coord.S_e}

        lag_ns = time.perf_counter_ns() - start_time

        return OperationResult(
            operation_type=OperationType.MEASURE,
            input_coords=[coord],
            output_coords=[coord],  # Measurement doesn't change the coordinate
            entropy_generated=measurement_entropy,
            lag_ns=lag_ns,
            metadata={
                "measured_values": measured,
                "precision": self.precision,
            }
        )


@dataclass
class TransformOp:
    """
    Transform operation: change coordinate representation.

    Transforms convert between coordinate systems:
    - PartitionCoordinate ↔ SCoordinate
    - Different bases within same system
    - Projections onto subspaces

    Transforms are entropy-neutral when exact (bijective).

    Attributes:
        target_type: "partition" or "s_coordinate"
        preserve_structure: Whether to preserve geometric relationships
    """
    target_type: str = "s_coordinate"
    preserve_structure: bool = True

    def apply(
        self,
        coord: SCoordinate | PartitionCoordinate
    ) -> OperationResult:
        """Transform coordinate to target representation."""
        start_time = time.perf_counter_ns()

        if self.target_type == "s_coordinate":
            if isinstance(coord, PartitionCoordinate):
                result = SCoordinate.from_partition(coord)
            else:
                result = coord  # Already S-coordinate
        elif self.target_type == "partition":
            if isinstance(coord, SCoordinate):
                # Approximate inverse mapping (not exact)
                n = max(1, int(coord.S_k * 6 + 1))
                l = min(n - 1, max(0, int(coord.S_t * n)))
                m = int((coord.S_e - 0.5) * 2 * l) if l > 0 else 0
                s = 0.5 if coord.total_entropy % 1 < 0.5 else -0.5
                result = PartitionCoordinate(n=n, l=l, m=m, s=s)
            else:
                result = coord  # Already partition coordinate
        else:
            raise ValueError(f"Unknown target type: {self.target_type}")

        lag_ns = time.perf_counter_ns() - start_time

        # Transforms are entropy-neutral when bijective
        # But approximate transforms generate small entropy
        entropy = 0.0 if self.preserve_structure else K_B * 0.1

        return OperationResult(
            operation_type=OperationType.TRANSFORM,
            input_coords=[coord],
            output_coords=[result],
            entropy_generated=entropy,
            lag_ns=lag_ns,
            metadata={"target_type": self.target_type}
        )


# Compound operations (built from primitives)

def partition_compose_cycle(
    coord: SCoordinate,
    n_parts: int = 2
) -> Tuple[OperationResult, OperationResult, float]:
    """
    Demonstrate irreversibility: Partition then Compose.

    Returns the two operation results and the entropy generated.
    The key insight: the composed result is NOT equal to the original.
    """
    partition_op = PartitionOp(n_parts=n_parts)
    compose_op = ComposeOp(mode="mean")

    # Partition
    partition_result = partition_op.apply(coord)

    # Compose the parts back
    compose_result = compose_op.apply(partition_result.output_coords)

    # Total entropy (second law: always positive)
    total_entropy = partition_result.entropy_generated + compose_result.entropy_generated

    # The composed result differs from original
    # This difference is the "thermodynamic cost" of the cycle

    return partition_result, compose_result, total_entropy


def traverse_to_terminal(
    start: SCoordinate,
    terminal: TerminalState,
    step_size: float = 0.1
) -> List[OperationResult]:
    """
    Traverse from start to a terminal state.

    For terminal states with multiple coordinates, finds paths
    to each and returns all traversals.
    """
    results = []

    for coord in terminal.coordinates:
        target_s = SCoordinate.from_partition(coord)
        traverse_op = TraverseOp(target=target_s, path_type="direct")
        result = traverse_op.apply(start, step_size=step_size)
        results.append(result)

    return results
